apiVersion: apps/v1
kind: Deployment
metadata:
  name: lp
  labels:
    app: lp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lp
  template:
    metadata:
      labels:
        app: lp
    spec:
      containers:
      - name: lp
        image: sddswd/lp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Service
apiVersion: v1
metadata:
  name: lp
spec:
  selector:
    app: lp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lp
  labels:
    app: lp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: lp.mezi.web.id
    http:
      paths:
      - path: /
        backend:
          serviceName: lp
          servicePort: 80